/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Meta */
        get: operations["meta_v1_meta_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/seasons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Seasons */
        get: operations["list_seasons_v1_seasons_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/seasons/{season_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Season Summary */
        get: operations["get_season_summary_v1_seasons__season_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/seasons/{season_id}/standings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Standings */
        get: operations["get_standings_v1_seasons__season_id__standings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/seasons/{season_id}/standings/timeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Standings Timeline */
        get: operations["get_standings_timeline_v1_seasons__season_id__standings_timeline_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/owners": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Owners */
        get: operations["list_owners_v1_owners_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/owners/rivalry-matrix": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Rivalry Matrix */
        get: operations["get_rivalry_matrix_v1_owners_rivalry_matrix_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/owners/{owner_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Owner Career */
        get: operations["get_owner_career_v1_owners__owner_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/owners/{owner_id}/seasons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Owner Seasons */
        get: operations["get_owner_seasons_v1_owners__owner_id__seasons_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/owners/{owner_id}/trajectory": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Owner Trajectory */
        get: operations["get_owner_trajectory_v1_owners__owner_id__trajectory_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/owners/{owner_id}/head-to-head/{other_owner_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Head To Head */
        get: operations["get_head_to_head_v1_owners__owner_id__head_to_head__other_owner_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/records": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Records */
        get: operations["get_records_v1_records_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/records/championships": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Championships */
        get: operations["get_championships_v1_records_championships_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/players": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Players */
        get: operations["list_players_v1_players_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/players/{player_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Player Detail */
        get: operations["get_player_detail_v1_players__player_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/players/{player_id}/scoring": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Player Scoring */
        get: operations["get_player_scoring_v1_players__player_id__scoring_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/players/{player_id}/ownership": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Player Ownership */
        get: operations["get_player_ownership_v1_players__player_id__ownership_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/players/{player_id}/availability": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Player Availability */
        get: operations["get_player_availability_v1_players__player_id__availability_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/stats/top-scorers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Top Scorers */
        get: operations["get_top_scorers_v1_stats_top_scorers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/stats/season-totals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Season Totals */
        get: operations["get_season_totals_v1_stats_season_totals_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AvailabilityWeek */
        AvailabilityWeek: {
            /** Week */
            week: number;
            /** Status */
            status: string;
            /** Owning Team Id */
            owning_team_id?: number | null;
            /** Is Pre Kickoff Snapshot */
            is_pre_kickoff_snapshot: boolean;
        };
        /** ChampionshipEntry */
        ChampionshipEntry: {
            /** Season Year */
            season_year: number;
            champion?: components["schemas"]["TeamRef"] | null;
            runner_up?: components["schemas"]["TeamRef"] | null;
            last_place?: components["schemas"]["TeamRef"] | null;
        };
        /** ChampionshipHistory */
        ChampionshipHistory: {
            /** Seasons */
            seasons: components["schemas"]["ChampionshipEntry"][];
        };
        /**
         * Coverage
         * @description What in the database is trustworthy, partial, or absent.
         *
         *     Mirrors the reliability map in ``docs/03_DATA_ACCESS.md`` so the frontend
         *     can render honest gap affordances rather than fabricated zeros.
         */
        Coverage: {
            /** Seasons Present */
            seasons_present: number[];
            /** Seasons Scored */
            seasons_scored: number[];
            /** Scored Year Min */
            scored_year_min?: number | null;
            /** Scored Year Max */
            scored_year_max?: number | null;
            /** Reconstruction Complete */
            reconstruction_complete: boolean;
            /**
             * Availability Current Season Only
             * @default true
             */
            availability_current_season_only: boolean;
            /**
             * Dst Scoring Complete
             * @default false
             */
            dst_scoring_complete: boolean;
        };
        /** Envelope[ChampionshipHistory] */
        Envelope_ChampionshipHistory_: {
            data: components["schemas"]["ChampionshipHistory"];
            meta: components["schemas"]["Meta"];
        };
        /** Envelope[HeadToHead] */
        Envelope_HeadToHead_: {
            data: components["schemas"]["HeadToHead"];
            meta: components["schemas"]["Meta"];
        };
        /** Envelope[MetaResponse] */
        Envelope_MetaResponse_: {
            data: components["schemas"]["MetaResponse"];
            meta: components["schemas"]["Meta"];
        };
        /** Envelope[OwnerCareer] */
        Envelope_OwnerCareer_: {
            data: components["schemas"]["OwnerCareer"];
            meta: components["schemas"]["Meta"];
        };
        /** Envelope[OwnerSeasons] */
        Envelope_OwnerSeasons_: {
            data: components["schemas"]["OwnerSeasons"];
            meta: components["schemas"]["Meta"];
        };
        /** Envelope[OwnerTrajectory] */
        Envelope_OwnerTrajectory_: {
            data: components["schemas"]["OwnerTrajectory"];
            meta: components["schemas"]["Meta"];
        };
        /** Envelope[OwnersList] */
        Envelope_OwnersList_: {
            data: components["schemas"]["OwnersList"];
            meta: components["schemas"]["Meta"];
        };
        /** Envelope[PlayerAvailability] */
        Envelope_PlayerAvailability_: {
            data: components["schemas"]["PlayerAvailability"];
            meta: components["schemas"]["Meta"];
        };
        /** Envelope[PlayerIndex] */
        Envelope_PlayerIndex_: {
            data: components["schemas"]["PlayerIndex"];
            meta: components["schemas"]["Meta"];
        };
        /** Envelope[PlayerOut] */
        Envelope_PlayerOut_: {
            data: components["schemas"]["PlayerOut"];
            meta: components["schemas"]["Meta"];
        };
        /** Envelope[PlayerOwnership] */
        Envelope_PlayerOwnership_: {
            data: components["schemas"]["PlayerOwnership"];
            meta: components["schemas"]["Meta"];
        };
        /** Envelope[PlayerScoring] */
        Envelope_PlayerScoring_: {
            data: components["schemas"]["PlayerScoring"];
            meta: components["schemas"]["Meta"];
        };
        /** Envelope[RecordsBook] */
        Envelope_RecordsBook_: {
            data: components["schemas"]["RecordsBook"];
            meta: components["schemas"]["Meta"];
        };
        /** Envelope[RivalryMatrix] */
        Envelope_RivalryMatrix_: {
            data: components["schemas"]["RivalryMatrix"];
            meta: components["schemas"]["Meta"];
        };
        /** Envelope[SeasonList] */
        Envelope_SeasonList_: {
            data: components["schemas"]["SeasonList"];
            meta: components["schemas"]["Meta"];
        };
        /** Envelope[SeasonSummary] */
        Envelope_SeasonSummary_: {
            data: components["schemas"]["SeasonSummary"];
            meta: components["schemas"]["Meta"];
        };
        /** Envelope[SeasonTotals] */
        Envelope_SeasonTotals_: {
            data: components["schemas"]["SeasonTotals"];
            meta: components["schemas"]["Meta"];
        };
        /** Envelope[StandingsTimeline] */
        Envelope_StandingsTimeline_: {
            data: components["schemas"]["StandingsTimeline"];
            meta: components["schemas"]["Meta"];
        };
        /** Envelope[Standings] */
        Envelope_Standings_: {
            data: components["schemas"]["Standings"];
            meta: components["schemas"]["Meta"];
        };
        /** Envelope[TopScorers] */
        Envelope_TopScorers_: {
            data: components["schemas"]["TopScorers"];
            meta: components["schemas"]["Meta"];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HeadToHead */
        HeadToHead: {
            owner_a: components["schemas"]["OwnerRef"];
            owner_b: components["schemas"]["OwnerRef"];
            /** Available */
            available: boolean;
            /** Games Played */
            games_played: number;
            /** Reason */
            reason?: string | null;
        } & {
            [key: string]: unknown;
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @default ok
             */
            status: string;
        };
        /** LatestRun */
        LatestRun: {
            /** Run Id */
            run_id?: number | null;
            /** Status */
            status?: string | null;
            /** Mode */
            mode?: string | null;
            /** Started At */
            started_at?: string | null;
            /** Finished At */
            finished_at?: string | null;
        };
        /**
         * Meta
         * @description Audit metadata attached to every API response.
         *
         *     * ``last_updated`` — ISO timestamp of the underlying data (the
         *       entity's ``updated_at`` for single-resource endpoints, max across
         *       collection rows otherwise).
         *     * ``source`` — which crawler / pipeline stage produced the data.
         *     * ``pipeline_run_id`` — most recent successful pipeline run touching
         *       the relevant data, or null if the pipeline has never run.
         */
        Meta: {
            /** Last Updated */
            last_updated?: string | null;
            /**
             * Source
             * @default pipeline
             */
            source: string;
            /** Pipeline Run Id */
            pipeline_run_id?: number | null;
        };
        /** MetaResponse */
        MetaResponse: {
            latest_run: components["schemas"]["LatestRun"];
            coverage: components["schemas"]["Coverage"];
        };
        /** OwnerCareer */
        OwnerCareer: {
            /** Owner Id */
            owner_id: number;
            /** Display Name */
            display_name?: string | null;
            /** Seasons Played */
            seasons_played: number;
            /** Total Wins */
            total_wins: number;
            /** Total Losses */
            total_losses: number;
            /** Total Ties */
            total_ties: number;
            /** Total Points For */
            total_points_for: number;
            /** Championships */
            championships: number;
            /** Best Finish */
            best_finish?: number | null;
            /** Avg Finish */
            avg_finish?: number | null;
            /**
             * Trophy Case
             * @default []
             */
            trophy_case: components["schemas"]["TrophyEntry"][];
        };
        /** OwnerRef */
        OwnerRef: {
            /** Owner Id */
            owner_id: number;
            /** Display Name */
            display_name?: string | null;
        };
        /** OwnerSeasonRow */
        OwnerSeasonRow: {
            /** Season Id */
            season_id: number;
            /** Season Year */
            season_year?: number | null;
            /** Team Id */
            team_id: number;
            /** Team Name */
            team_name?: string | null;
            /** Wins */
            wins: number;
            /** Losses */
            losses: number;
            /** Ties */
            ties: number;
            /** Points For */
            points_for: number;
            /** Final Rank */
            final_rank?: number | null;
            /** Made Playoffs */
            made_playoffs?: boolean | null;
            /** Is Champion */
            is_champion: boolean;
        };
        /** OwnerSeasons */
        OwnerSeasons: {
            /** Owner Id */
            owner_id: number;
            /** Display Name */
            display_name?: string | null;
            /** Seasons */
            seasons: components["schemas"]["OwnerSeasonRow"][];
        };
        /** OwnerTrajectory */
        OwnerTrajectory: {
            /** Owner Id */
            owner_id: number;
            /** Display Name */
            display_name?: string | null;
            /** Points */
            points: components["schemas"]["TrajectoryPoint"][];
        };
        /** OwnersList */
        OwnersList: {
            /** Owners */
            owners: components["schemas"]["OwnerCareer"][];
        };
        /** OwnershipEvent */
        OwnershipEvent: {
            /** Team Id */
            team_id: number;
            /** Team Name */
            team_name?: string | null;
            /** Season Year */
            season_year: number;
            /** Week */
            week: number;
            /** Roster Slot */
            roster_slot?: string | null;
            /** Acquisition Type */
            acquisition_type?: string | null;
        };
        /** PlayerAvailability */
        PlayerAvailability: {
            /** Player Id */
            player_id: number;
            /** Season Year */
            season_year: number;
            /** Available */
            available: boolean;
            /** Reason */
            reason?: string | null;
            /** Weeks */
            weeks: components["schemas"]["AvailabilityWeek"][];
        };
        /** PlayerIndex */
        PlayerIndex: {
            /** Players */
            players: components["schemas"]["PlayerLite"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** PlayerLite */
        PlayerLite: {
            /** Player Id */
            player_id: number;
            /** Name Full */
            name_full: string;
            /** Position */
            position?: string | null;
            /** Nfl Team */
            nfl_team?: string | null;
        };
        /** PlayerOut */
        PlayerOut: {
            /** Player Id */
            player_id: number;
            /** Name Full */
            name_full: string;
            /** Name First */
            name_first?: string | null;
            /** Name Last */
            name_last?: string | null;
            /** Position */
            position?: string | null;
            /** Nfl Team */
            nfl_team?: string | null;
            /** Birth Date */
            birth_date?: string | null;
            /** Rookie Year */
            rookie_year?: number | null;
            /** Is Active */
            is_active: boolean;
            /** Nfl Com Player Id */
            nfl_com_player_id?: string | null;
            /** Gsis Id */
            gsis_id?: string | null;
            /** Sleeper Id */
            sleeper_id?: string | null;
            /** Espn Id */
            espn_id?: string | null;
            /** Yahoo Id */
            yahoo_id?: string | null;
        };
        /** PlayerOwnership */
        PlayerOwnership: {
            /** Player Id */
            player_id: number;
            /** Events */
            events: components["schemas"]["OwnershipEvent"][];
        };
        /** PlayerScoring */
        PlayerScoring: {
            /** Player Id */
            player_id: number;
            /** Season Year */
            season_year: number;
            /** Available */
            available: boolean;
            /** Total Points */
            total_points?: number | null;
            /** Reason */
            reason?: string | null;
            /** Weeks */
            weeks: components["schemas"]["ScoringWeek"][];
        };
        /**
         * RecordsBook
         * @description Heterogeneous superlatives; each value is an availability-tagged object.
         *
         *     Kept extra-permissive so each record can carry its own context fields
         *     (matchup_id, player_id, owner_name, …) for deep-linking without a model per
         *     record. The frontend reads ``available`` first, then the value/context.
         */
        RecordsBook: {
            /** Scored Era */
            scored_era: number[];
        } & {
            [key: string]: unknown;
        };
        /** RivalryCell */
        RivalryCell: {
            /** A */
            a: number;
            /** B */
            b: number;
            /** Games */
            games: number;
            /** A Win Pct */
            a_win_pct?: number | null;
        };
        /** RivalryMatrix */
        RivalryMatrix: {
            /** Owners */
            owners: components["schemas"]["OwnerRef"][];
            /** Cells */
            cells: components["schemas"]["RivalryCell"][];
        };
        /** ScoringWeek */
        ScoringWeek: {
            /** Week */
            week: number;
            /** Points */
            points?: number | null;
            /**
             * Breakdown
             * @default {}
             */
            breakdown: {
                [key: string]: unknown;
            };
        };
        /** SeasonList */
        SeasonList: {
            /** Seasons */
            seasons: components["schemas"]["SeasonListItem"][];
        };
        /** SeasonListItem */
        SeasonListItem: {
            /** Season Id */
            season_id: number;
            /** Season Year */
            season_year: number;
            /** Status */
            status?: string | null;
            /** Is Scored */
            is_scored: boolean;
            champion?: components["schemas"]["TeamRef"] | null;
        };
        /** SeasonSummary */
        SeasonSummary: {
            /** Season Id */
            season_id: number;
            /** Season Year */
            season_year: number;
            /** Status */
            status?: string | null;
            /** Regular Season Weeks */
            regular_season_weeks?: number | null;
            /** Playoff Weeks */
            playoff_weeks?: number | null;
            champion?: components["schemas"]["TeamRef"] | null;
            runner_up?: components["schemas"]["TeamRef"] | null;
            last_place?: components["schemas"]["TeamRef"] | null;
        };
        /** SeasonTotal */
        SeasonTotal: {
            /** Player Id */
            player_id: number;
            /** Name Full */
            name_full: string;
            /** Position */
            position?: string | null;
            /** Nfl Team */
            nfl_team?: string | null;
            /** Total Points */
            total_points: number;
            /** Weeks Played */
            weeks_played: number;
        };
        /** SeasonTotals */
        SeasonTotals: {
            /** Season Year */
            season_year: number;
            /** Position */
            position?: string | null;
            /** Totals */
            totals: components["schemas"]["SeasonTotal"][];
        };
        /** StandingRow */
        StandingRow: {
            /** Rank */
            rank: number;
            /** Team Id */
            team_id: number;
            /** Team Name */
            team_name?: string | null;
            /** Owner Id */
            owner_id: number;
            /** Owner Name */
            owner_name?: string | null;
            /** Wins */
            wins: number;
            /** Losses */
            losses: number;
            /** Ties */
            ties: number;
            /** Points For */
            points_for: number;
            /** Points Against */
            points_against: number;
            /** Win Pct */
            win_pct: number;
            streak: components["schemas"]["Streak"];
            /** Final Rank */
            final_rank?: number | null;
        };
        /** Standings */
        Standings: {
            /** Season Id */
            season_id: number;
            /** Season Year */
            season_year: number;
            /** Through Week */
            through_week: number;
            /** Regular Season Weeks */
            regular_season_weeks: number;
            /** Rank Basis */
            rank_basis: string;
            /** Tiebreak Caveat */
            tiebreak_caveat: boolean;
            /** Rows */
            rows: components["schemas"]["StandingRow"][];
        };
        /** StandingsTimeline */
        StandingsTimeline: {
            /** Season Id */
            season_id: number;
            /** Season Year */
            season_year: number;
            /** Regular Season Weeks */
            regular_season_weeks: number;
            /** Teams */
            teams: components["schemas"]["TimelineTeam"][];
        };
        /** Streak */
        Streak: {
            /** Result */
            result?: string | null;
            /**
             * Length
             * @default 0
             */
            length: number;
        };
        /** TeamRef */
        TeamRef: {
            /** Team Id */
            team_id: number;
            /** Team Name */
            team_name?: string | null;
            /** Owner Id */
            owner_id?: number | null;
            /** Owner Name */
            owner_name?: string | null;
        };
        /** TimelinePoint */
        TimelinePoint: {
            /** Week */
            week: number;
            /** Rank */
            rank: number;
            /** Points For */
            points_for: number;
        };
        /** TimelineTeam */
        TimelineTeam: {
            /** Team Id */
            team_id: number;
            /** Team Name */
            team_name?: string | null;
            /** Owner Id */
            owner_id: number;
            /** Owner Name */
            owner_name?: string | null;
            /** Points */
            points: components["schemas"]["TimelinePoint"][];
        };
        /** TopScorer */
        TopScorer: {
            /** Player Id */
            player_id: number;
            /** Name Full */
            name_full: string;
            /** Position */
            position?: string | null;
            /** Nfl Team */
            nfl_team?: string | null;
            /** Season Year */
            season_year: number;
            /** Week */
            week?: number | null;
            /** Points */
            points: number;
        };
        /** TopScorers */
        TopScorers: {
            /** Season Year */
            season_year: number;
            /** Week */
            week?: number | null;
            /** Position */
            position?: string | null;
            /** Scorers */
            scorers: components["schemas"]["TopScorer"][];
        };
        /** TrajectoryPoint */
        TrajectoryPoint: {
            /** Season Year */
            season_year?: number | null;
            /** Final Rank */
            final_rank?: number | null;
            /** Points For */
            points_for: number;
        };
        /** TrophyEntry */
        TrophyEntry: {
            /** Season Year */
            season_year?: number | null;
            /** Team Name */
            team_name?: string | null;
            /** Finish */
            finish?: number | null;
            /** Is Champion */
            is_champion: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    meta_v1_meta_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_MetaResponse_"];
                };
            };
        };
    };
    list_seasons_v1_seasons_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_SeasonList_"];
                };
            };
        };
    };
    get_season_summary_v1_seasons__season_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                season_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_SeasonSummary_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_standings_v1_seasons__season_id__standings_get: {
        parameters: {
            query?: {
                through_week?: number | null;
            };
            header?: never;
            path: {
                season_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_Standings_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_standings_timeline_v1_seasons__season_id__standings_timeline_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                season_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_StandingsTimeline_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_owners_v1_owners_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_OwnersList_"];
                };
            };
        };
    };
    get_rivalry_matrix_v1_owners_rivalry_matrix_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_RivalryMatrix_"];
                };
            };
        };
    };
    get_owner_career_v1_owners__owner_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                owner_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_OwnerCareer_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_owner_seasons_v1_owners__owner_id__seasons_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                owner_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_OwnerSeasons_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_owner_trajectory_v1_owners__owner_id__trajectory_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                owner_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_OwnerTrajectory_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_head_to_head_v1_owners__owner_id__head_to_head__other_owner_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                owner_id: number;
                other_owner_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_HeadToHead_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_records_v1_records_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_RecordsBook_"];
                };
            };
        };
    };
    get_championships_v1_records_championships_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_ChampionshipHistory_"];
                };
            };
        };
    };
    list_players_v1_players_get: {
        parameters: {
            query?: {
                name?: string | null;
                position?: string | null;
                nfl_team?: string | null;
                active?: boolean | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_PlayerIndex_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_player_detail_v1_players__player_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                player_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_PlayerOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_player_scoring_v1_players__player_id__scoring_get: {
        parameters: {
            query: {
                season: number;
            };
            header?: never;
            path: {
                player_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_PlayerScoring_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_player_ownership_v1_players__player_id__ownership_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                player_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_PlayerOwnership_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_player_availability_v1_players__player_id__availability_get: {
        parameters: {
            query: {
                season: number;
            };
            header?: never;
            path: {
                player_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_PlayerAvailability_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_top_scorers_v1_stats_top_scorers_get: {
        parameters: {
            query: {
                season: number;
                week?: number | null;
                position?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_TopScorers_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_season_totals_v1_stats_season_totals_get: {
        parameters: {
            query: {
                season: number;
                position?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_SeasonTotals_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
