/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Meta */
        get: operations["meta_v1_meta_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/seasons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Seasons */
        get: operations["list_seasons_v1_seasons_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/seasons/{season_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Season Summary */
        get: operations["get_season_summary_v1_seasons__season_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/seasons/{season_id}/standings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Standings */
        get: operations["get_standings_v1_seasons__season_id__standings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/seasons/{season_id}/standings/timeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Standings Timeline */
        get: operations["get_standings_timeline_v1_seasons__season_id__standings_timeline_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/owners": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Owners */
        get: operations["list_owners_v1_owners_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/owners/rivalry-matrix": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Rivalry Matrix */
        get: operations["get_rivalry_matrix_v1_owners_rivalry_matrix_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/owners/{owner_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Owner Career */
        get: operations["get_owner_career_v1_owners__owner_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/owners/{owner_id}/seasons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Owner Seasons */
        get: operations["get_owner_seasons_v1_owners__owner_id__seasons_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/owners/{owner_id}/trajectory": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Owner Trajectory */
        get: operations["get_owner_trajectory_v1_owners__owner_id__trajectory_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/owners/{owner_id}/head-to-head/{other_owner_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Head To Head */
        get: operations["get_head_to_head_v1_owners__owner_id__head_to_head__other_owner_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/records": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Records */
        get: operations["get_records_v1_records_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/records/championships": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Championships */
        get: operations["get_championships_v1_records_championships_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/records/draft": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Draft Records */
        get: operations["get_draft_records_v1_records_draft_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/players": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Players */
        get: operations["list_players_v1_players_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/players/{player_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Player Detail */
        get: operations["get_player_detail_v1_players__player_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/players/{player_id}/scoring": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Player Scoring */
        get: operations["get_player_scoring_v1_players__player_id__scoring_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/players/{player_id}/ownership": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Player Ownership */
        get: operations["get_player_ownership_v1_players__player_id__ownership_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/players/{player_id}/availability": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Player Availability */
        get: operations["get_player_availability_v1_players__player_id__availability_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/stats/top-scorers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Top Scorers */
        get: operations["get_top_scorers_v1_stats_top_scorers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/stats/season-totals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Season Totals */
        get: operations["get_season_totals_v1_stats_season_totals_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/seasons/{season_id}/weeks/{week}/matchups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Week Matchups */
        get: operations["get_week_matchups_v1_seasons__season_id__weeks__week__matchups_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/matchups/{matchup_id}/box-score": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Box Score */
        get: operations["get_box_score_v1_matchups__matchup_id__box_score_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/seasons/{season_id}/draft": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Draft Board */
        get: operations["get_draft_board_v1_seasons__season_id__draft_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/seasons/{season_id}/draft/value": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Draft Value */
        get: operations["get_draft_value_v1_seasons__season_id__draft_value_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/seasons/{season_id}/power": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Power Ranking */
        get: operations["get_power_ranking_v1_seasons__season_id__power_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/seasons/{season_id}/power/timeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Power Timeline */
        get: operations["get_power_timeline_v1_seasons__season_id__power_timeline_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/teams/{team_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Team Overview */
        get: operations["get_team_overview_v1_teams__team_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/teams/{team_id}/roster": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Team Roster */
        get: operations["get_team_roster_v1_teams__team_id__roster_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/teams/{team_id}/schedule": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Team Schedule */
        get: operations["get_team_schedule_v1_teams__team_id__schedule_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/teams/{team_id}/scoring-trend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Team Scoring Trend */
        get: operations["get_team_scoring_trend_v1_teams__team_id__scoring_trend_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/teams/{team_id}/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Team Transactions */
        get: operations["get_team_transactions_v1_teams__team_id__transactions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search */
        get: operations["search_v1_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AvailabilityWeek */
        AvailabilityWeek: {
            /** Week */
            week: number;
            /** Status */
            status: string;
            /** Owning Team Id */
            owning_team_id?: number | null;
            /** Is Pre Kickoff Snapshot */
            is_pre_kickoff_snapshot: boolean;
        };
        /** BoxPlayer */
        BoxPlayer: {
            /** Roster Slot */
            roster_slot?: string | null;
            /** Player Id */
            player_id: number;
            /** Player Name */
            player_name?: string | null;
            /** Position */
            position?: string | null;
            /** League Points */
            league_points?: number | null;
            /** Is Starter */
            is_starter: boolean;
            /**
             * Breakdown
             * @default {}
             */
            breakdown: {
                [key: string]: unknown;
            };
            /** Projection */
            projection?: number | null;
            /**
             * Available
             * @default true
             */
            available: boolean;
            /** Reason */
            reason?: string | null;
        };
        /** BoxScore */
        BoxScore: {
            /** Matchup Id */
            matchup_id: number;
            /** Season Year */
            season_year?: number | null;
            /** Week */
            week: number;
            /** Available */
            available: boolean;
            /** Reason */
            reason?: string | null;
            /**
             * Is Playoff
             * @default false
             */
            is_playoff: boolean;
            home?: components["schemas"]["BoxTeam"] | null;
            away?: components["schemas"]["BoxTeam"] | null;
            /** Winner Team Id */
            winner_team_id?: number | null;
        };
        /** BoxTeam */
        BoxTeam: {
            /** Team Id */
            team_id: number;
            /** Team Name */
            team_name?: string | null;
            /** Owner Name */
            owner_name?: string | null;
            /** Total Score */
            total_score?: number | null;
            /** Starter Points */
            starter_points: number;
            /** Bench Points */
            bench_points: number;
            /** Optimal Total */
            optimal_total: number;
            /** Points Left On Bench */
            points_left_on_bench: number;
            /** Beat Projection By */
            beat_projection_by?: number | null;
            /** Lineup */
            lineup: components["schemas"]["BoxPlayer"][];
        };
        /** ChampionshipEntry */
        ChampionshipEntry: {
            /** Season Year */
            season_year: number;
            champion?: components["schemas"]["TeamRef"] | null;
            runner_up?: components["schemas"]["TeamRef"] | null;
            last_place?: components["schemas"]["TeamRef"] | null;
        };
        /** ChampionshipHistory */
        ChampionshipHistory: {
            /** Seasons */
            seasons: components["schemas"]["ChampionshipEntry"][];
        };
        /**
         * Coverage
         * @description What in the database is trustworthy, partial, or absent.
         *
         *     Mirrors the reliability map in ``docs/03_DATA_ACCESS.md`` so the frontend
         *     can render honest gap affordances rather than fabricated zeros.
         */
        Coverage: {
            /** Seasons Present */
            seasons_present: number[];
            /** Seasons Scored */
            seasons_scored: number[];
            /** Scored Year Min */
            scored_year_min?: number | null;
            /** Scored Year Max */
            scored_year_max?: number | null;
            /** Reconstruction Complete */
            reconstruction_complete: boolean;
            /**
             * Availability Current Season Only
             * @default true
             */
            availability_current_season_only: boolean;
            /**
             * Dst Scoring Complete
             * @default false
             */
            dst_scoring_complete: boolean;
        };
        /** DraftBoard */
        DraftBoard: {
            /** Season Id */
            season_id: number;
            /** Season Year */
            season_year: number;
            /** Available */
            available: boolean;
            /** Reason */
            reason?: string | null;
            /** Num Teams */
            num_teams?: number | null;
            /** Rounds */
            rounds: components["schemas"]["DraftRound"][];
        };
        /** DraftPick */
        DraftPick: {
            /** Overall */
            overall: number;
            /** Round */
            round: number;
            /** Pick In Round */
            pick_in_round: number;
            /** Team Id */
            team_id: number;
            /** Team Name */
            team_name?: string | null;
            /** Owner Id */
            owner_id?: number | null;
            /** Owner Name */
            owner_name?: string | null;
            /** Player Id */
            player_id: number;
            /** Player Name */
            player_name?: string | null;
            /** Position */
            position?: string | null;
            /** Season Year */
            season_year?: number | null;
            /** Season Points */
            season_points?: number | null;
            /** Value */
            value?: number | null;
            /**
             * Available
             * @default true
             */
            available: boolean;
            /** Reason */
            reason?: string | null;
        };
        /** DraftRecords */
        DraftRecords: {
            /** Available */
            available: boolean;
            /** Reason */
            reason?: string | null;
            /** Definition */
            definition: string;
            /** Best Picks */
            best_picks: components["schemas"]["DraftPick"][];
            /** Worst Picks */
            worst_picks: components["schemas"]["DraftPick"][];
        };
        /** DraftRound */
        DraftRound: {
            /** Round */
            round: number;
            /** Picks */
            picks: components["schemas"]["DraftPick"][];
        };
        /** DraftValue */
        DraftValue: {
            /** Season Id */
            season_id: number;
            /** Season Year */
            season_year: number;
            /** Available */
            available: boolean;
            /** Reason */
            reason?: string | null;
            /** Definition */
            definition: string;
            /** Slot Window */
            slot_window: number;
            /** Picks */
            picks: components["schemas"]["DraftPick"][];
            /** Steals */
            steals: components["schemas"]["DraftPick"][];
            /** Busts */
            busts: components["schemas"]["DraftPick"][];
        };
        /** Envelope[BoxScore] */
        Envelope_BoxScore_: {
            data: components["schemas"]["BoxScore"];
            meta: components["schemas"]["Meta"];
        };
        /** Envelope[ChampionshipHistory] */
        Envelope_ChampionshipHistory_: {
            data: components["schemas"]["ChampionshipHistory"];
            meta: components["schemas"]["Meta"];
        };
        /** Envelope[DraftBoard] */
        Envelope_DraftBoard_: {
            data: components["schemas"]["DraftBoard"];
            meta: components["schemas"]["Meta"];
        };
        /** Envelope[DraftRecords] */
        Envelope_DraftRecords_: {
            data: components["schemas"]["DraftRecords"];
            meta: components["schemas"]["Meta"];
        };
        /** Envelope[DraftValue] */
        Envelope_DraftValue_: {
            data: components["schemas"]["DraftValue"];
            meta: components["schemas"]["Meta"];
        };
        /** Envelope[HeadToHead] */
        Envelope_HeadToHead_: {
            data: components["schemas"]["HeadToHead"];
            meta: components["schemas"]["Meta"];
        };
        /** Envelope[MetaResponse] */
        Envelope_MetaResponse_: {
            data: components["schemas"]["MetaResponse"];
            meta: components["schemas"]["Meta"];
        };
        /** Envelope[OwnerCareer] */
        Envelope_OwnerCareer_: {
            data: components["schemas"]["OwnerCareer"];
            meta: components["schemas"]["Meta"];
        };
        /** Envelope[OwnerSeasons] */
        Envelope_OwnerSeasons_: {
            data: components["schemas"]["OwnerSeasons"];
            meta: components["schemas"]["Meta"];
        };
        /** Envelope[OwnerTrajectory] */
        Envelope_OwnerTrajectory_: {
            data: components["schemas"]["OwnerTrajectory"];
            meta: components["schemas"]["Meta"];
        };
        /** Envelope[OwnersList] */
        Envelope_OwnersList_: {
            data: components["schemas"]["OwnersList"];
            meta: components["schemas"]["Meta"];
        };
        /** Envelope[PlayerAvailability] */
        Envelope_PlayerAvailability_: {
            data: components["schemas"]["PlayerAvailability"];
            meta: components["schemas"]["Meta"];
        };
        /** Envelope[PlayerIndex] */
        Envelope_PlayerIndex_: {
            data: components["schemas"]["PlayerIndex"];
            meta: components["schemas"]["Meta"];
        };
        /** Envelope[PlayerOut] */
        Envelope_PlayerOut_: {
            data: components["schemas"]["PlayerOut"];
            meta: components["schemas"]["Meta"];
        };
        /** Envelope[PlayerOwnership] */
        Envelope_PlayerOwnership_: {
            data: components["schemas"]["PlayerOwnership"];
            meta: components["schemas"]["Meta"];
        };
        /** Envelope[PlayerScoring] */
        Envelope_PlayerScoring_: {
            data: components["schemas"]["PlayerScoring"];
            meta: components["schemas"]["Meta"];
        };
        /** Envelope[PowerRanking] */
        Envelope_PowerRanking_: {
            data: components["schemas"]["PowerRanking"];
            meta: components["schemas"]["Meta"];
        };
        /** Envelope[PowerTimeline] */
        Envelope_PowerTimeline_: {
            data: components["schemas"]["PowerTimeline"];
            meta: components["schemas"]["Meta"];
        };
        /** Envelope[RecordsBook] */
        Envelope_RecordsBook_: {
            data: components["schemas"]["RecordsBook"];
            meta: components["schemas"]["Meta"];
        };
        /** Envelope[RivalryMatrix] */
        Envelope_RivalryMatrix_: {
            data: components["schemas"]["RivalryMatrix"];
            meta: components["schemas"]["Meta"];
        };
        /** Envelope[SearchResults] */
        Envelope_SearchResults_: {
            data: components["schemas"]["SearchResults"];
            meta: components["schemas"]["Meta"];
        };
        /** Envelope[SeasonList] */
        Envelope_SeasonList_: {
            data: components["schemas"]["SeasonList"];
            meta: components["schemas"]["Meta"];
        };
        /** Envelope[SeasonSummary] */
        Envelope_SeasonSummary_: {
            data: components["schemas"]["SeasonSummary"];
            meta: components["schemas"]["Meta"];
        };
        /** Envelope[SeasonTotals] */
        Envelope_SeasonTotals_: {
            data: components["schemas"]["SeasonTotals"];
            meta: components["schemas"]["Meta"];
        };
        /** Envelope[StandingsTimeline] */
        Envelope_StandingsTimeline_: {
            data: components["schemas"]["StandingsTimeline"];
            meta: components["schemas"]["Meta"];
        };
        /** Envelope[Standings] */
        Envelope_Standings_: {
            data: components["schemas"]["Standings"];
            meta: components["schemas"]["Meta"];
        };
        /** Envelope[TeamOverview] */
        Envelope_TeamOverview_: {
            data: components["schemas"]["TeamOverview"];
            meta: components["schemas"]["Meta"];
        };
        /** Envelope[TeamRosterOut] */
        Envelope_TeamRosterOut_: {
            data: components["schemas"]["TeamRosterOut"];
            meta: components["schemas"]["Meta"];
        };
        /** Envelope[TeamSchedule] */
        Envelope_TeamSchedule_: {
            data: components["schemas"]["TeamSchedule"];
            meta: components["schemas"]["Meta"];
        };
        /** Envelope[TeamScoringTrend] */
        Envelope_TeamScoringTrend_: {
            data: components["schemas"]["TeamScoringTrend"];
            meta: components["schemas"]["Meta"];
        };
        /** Envelope[TeamTransactions] */
        Envelope_TeamTransactions_: {
            data: components["schemas"]["TeamTransactions"];
            meta: components["schemas"]["Meta"];
        };
        /** Envelope[TopScorers] */
        Envelope_TopScorers_: {
            data: components["schemas"]["TopScorers"];
            meta: components["schemas"]["Meta"];
        };
        /** Envelope[WeekMatchups] */
        Envelope_WeekMatchups_: {
            data: components["schemas"]["WeekMatchups"];
            meta: components["schemas"]["Meta"];
        };
        /**
         * GameCard
         * @description One game, folded back from Phase 1's two perspective rows. ``matchup_id``
         *     deep-links to the box score.
         */
        GameCard: {
            /** Matchup Id */
            matchup_id: number;
            /**
             * Is Playoff
             * @default false
             */
            is_playoff: boolean;
            team_a?: components["schemas"]["GameTeam"] | null;
            team_b?: components["schemas"]["GameTeam"] | null;
            /** Margin */
            margin?: number | null;
            /** Winner Team Id */
            winner_team_id?: number | null;
        };
        /** GameTeam */
        GameTeam: {
            /** Team Id */
            team_id: number;
            /** Team Name */
            team_name?: string | null;
            /** Owner Name */
            owner_name?: string | null;
            /** Score */
            score?: number | null;
            /**
             * Is Winner
             * @default false
             */
            is_winner: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HeadToHead */
        HeadToHead: {
            owner_a: components["schemas"]["OwnerRef"];
            owner_b: components["schemas"]["OwnerRef"];
            /** Available */
            available: boolean;
            /** Games Played */
            games_played: number;
            /** Reason */
            reason?: string | null;
        } & {
            [key: string]: unknown;
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @default ok
             */
            status: string;
        };
        /** LatestRun */
        LatestRun: {
            /** Run Id */
            run_id?: number | null;
            /** Status */
            status?: string | null;
            /** Mode */
            mode?: string | null;
            /** Started At */
            started_at?: string | null;
            /** Finished At */
            finished_at?: string | null;
        };
        /**
         * Meta
         * @description Audit metadata attached to every API response.
         *
         *     * ``last_updated`` — ISO timestamp of the underlying data (the
         *       entity's ``updated_at`` for single-resource endpoints, max across
         *       collection rows otherwise).
         *     * ``source`` — which crawler / pipeline stage produced the data.
         *     * ``pipeline_run_id`` — most recent successful pipeline run touching
         *       the relevant data, or null if the pipeline has never run.
         */
        Meta: {
            /** Last Updated */
            last_updated?: string | null;
            /**
             * Source
             * @default pipeline
             */
            source: string;
            /** Pipeline Run Id */
            pipeline_run_id?: number | null;
        };
        /** MetaResponse */
        MetaResponse: {
            latest_run: components["schemas"]["LatestRun"];
            coverage: components["schemas"]["Coverage"];
        };
        /** OwnerCareer */
        OwnerCareer: {
            /** Owner Id */
            owner_id: number;
            /** Display Name */
            display_name?: string | null;
            /** Seasons Played */
            seasons_played: number;
            /** Total Wins */
            total_wins: number;
            /** Total Losses */
            total_losses: number;
            /** Total Ties */
            total_ties: number;
            /** Total Points For */
            total_points_for: number;
            /** Championships */
            championships: number;
            /** Best Finish */
            best_finish?: number | null;
            /** Avg Finish */
            avg_finish?: number | null;
            /**
             * Trophy Case
             * @default []
             */
            trophy_case: components["schemas"]["TrophyEntry"][];
        };
        /** OwnerRef */
        OwnerRef: {
            /** Owner Id */
            owner_id: number;
            /** Display Name */
            display_name?: string | null;
        };
        /** OwnerSeasonRow */
        OwnerSeasonRow: {
            /** Season Id */
            season_id: number;
            /** Season Year */
            season_year?: number | null;
            /** Team Id */
            team_id: number;
            /** Team Name */
            team_name?: string | null;
            /** Wins */
            wins: number;
            /** Losses */
            losses: number;
            /** Ties */
            ties: number;
            /** Points For */
            points_for: number;
            /** Final Rank */
            final_rank?: number | null;
            /** Made Playoffs */
            made_playoffs?: boolean | null;
            /** Is Champion */
            is_champion: boolean;
        };
        /** OwnerSeasons */
        OwnerSeasons: {
            /** Owner Id */
            owner_id: number;
            /** Display Name */
            display_name?: string | null;
            /** Seasons */
            seasons: components["schemas"]["OwnerSeasonRow"][];
        };
        /** OwnerTrajectory */
        OwnerTrajectory: {
            /** Owner Id */
            owner_id: number;
            /** Display Name */
            display_name?: string | null;
            /** Points */
            points: components["schemas"]["TrajectoryPoint"][];
        };
        /** OwnersList */
        OwnersList: {
            /** Owners */
            owners: components["schemas"]["OwnerCareer"][];
        };
        /** OwnershipEvent */
        OwnershipEvent: {
            /** Team Id */
            team_id: number;
            /** Team Name */
            team_name?: string | null;
            /** Season Year */
            season_year: number;
            /** Week */
            week: number;
            /** Roster Slot */
            roster_slot?: string | null;
            /** Acquisition Type */
            acquisition_type?: string | null;
        };
        /** PlayerAvailability */
        PlayerAvailability: {
            /** Player Id */
            player_id: number;
            /** Season Year */
            season_year: number;
            /** Available */
            available: boolean;
            /** Reason */
            reason?: string | null;
            /** Weeks */
            weeks: components["schemas"]["AvailabilityWeek"][];
        };
        /** PlayerIndex */
        PlayerIndex: {
            /** Players */
            players: components["schemas"]["PlayerLite"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** PlayerLite */
        PlayerLite: {
            /** Player Id */
            player_id: number;
            /** Name Full */
            name_full: string;
            /** Position */
            position?: string | null;
            /** Nfl Team */
            nfl_team?: string | null;
        };
        /** PlayerOut */
        PlayerOut: {
            /** Player Id */
            player_id: number;
            /** Name Full */
            name_full: string;
            /** Name First */
            name_first?: string | null;
            /** Name Last */
            name_last?: string | null;
            /** Position */
            position?: string | null;
            /** Nfl Team */
            nfl_team?: string | null;
            /** Birth Date */
            birth_date?: string | null;
            /** Rookie Year */
            rookie_year?: number | null;
            /** Is Active */
            is_active: boolean;
            /** Nfl Com Player Id */
            nfl_com_player_id?: string | null;
            /** Gsis Id */
            gsis_id?: string | null;
            /** Sleeper Id */
            sleeper_id?: string | null;
            /** Espn Id */
            espn_id?: string | null;
            /** Yahoo Id */
            yahoo_id?: string | null;
        };
        /** PlayerOwnership */
        PlayerOwnership: {
            /** Player Id */
            player_id: number;
            /** Events */
            events: components["schemas"]["OwnershipEvent"][];
        };
        /** PlayerScoring */
        PlayerScoring: {
            /** Player Id */
            player_id: number;
            /** Season Year */
            season_year: number;
            /** Available */
            available: boolean;
            /** Total Points */
            total_points?: number | null;
            /** Reason */
            reason?: string | null;
            /** Weeks */
            weeks: components["schemas"]["ScoringWeek"][];
        };
        /** PowerRanking */
        PowerRanking: {
            /** Season Id */
            season_id: number;
            /** Season Year */
            season_year: number;
            /** Through Week */
            through_week: number;
            /** Regular Season Weeks */
            regular_season_weeks: number;
            /** Weights */
            weights: {
                [key: string]: number;
            };
            /** Explainer */
            explainer: string;
            /** Rows */
            rows: components["schemas"]["PowerRow"][];
        };
        /** PowerRow */
        PowerRow: {
            /** Rank */
            rank: number;
            /** Team Id */
            team_id: number;
            /** Team Name */
            team_name?: string | null;
            /** Owner Id */
            owner_id: number;
            /** Owner Name */
            owner_name?: string | null;
            /** Wins */
            wins: number;
            /** Losses */
            losses: number;
            /** Ties */
            ties: number;
            /** Points For */
            points_for: number;
            /** Power Score */
            power_score: number;
            /** Points For Per Game */
            points_for_per_game: number;
            /** Win Pct */
            win_pct: number;
            /** Recent Points For Per Game */
            recent_points_for_per_game: number;
            /** Z Points For */
            z_points_for: number;
            /** Z Win Pct */
            z_win_pct: number;
            /** Z Recent */
            z_recent: number;
            /** Standings Rank */
            standings_rank: number;
            /** Rank Delta */
            rank_delta: number;
        };
        /** PowerTimeline */
        PowerTimeline: {
            /** Season Id */
            season_id: number;
            /** Season Year */
            season_year: number;
            /** Regular Season Weeks */
            regular_season_weeks: number;
            /** Teams */
            teams: components["schemas"]["PowerTimelineTeam"][];
        };
        /** PowerTimelinePoint */
        PowerTimelinePoint: {
            /** Week */
            week: number;
            /** Rank */
            rank: number;
            /** Power Score */
            power_score: number;
        };
        /** PowerTimelineTeam */
        PowerTimelineTeam: {
            /** Team Id */
            team_id: number;
            /** Team Name */
            team_name?: string | null;
            /** Owner Id */
            owner_id: number;
            /** Owner Name */
            owner_name?: string | null;
            /** Points */
            points: components["schemas"]["PowerTimelinePoint"][];
        };
        /**
         * RecordsBook
         * @description Heterogeneous superlatives; each value is an availability-tagged object.
         *
         *     Kept extra-permissive so each record can carry its own context fields
         *     (matchup_id, player_id, owner_name, …) for deep-linking without a model per
         *     record. The frontend reads ``available`` first, then the value/context.
         */
        RecordsBook: {
            /** Scored Era */
            scored_era: number[];
        } & {
            [key: string]: unknown;
        };
        /** RivalryCell */
        RivalryCell: {
            /** A */
            a: number;
            /** B */
            b: number;
            /** Games */
            games: number;
            /** A Win Pct */
            a_win_pct?: number | null;
        };
        /** RivalryMatrix */
        RivalryMatrix: {
            /** Owners */
            owners: components["schemas"]["OwnerRef"][];
            /** Cells */
            cells: components["schemas"]["RivalryCell"][];
        };
        /** ScheduleGame */
        ScheduleGame: {
            /** Matchup Id */
            matchup_id: number;
            /** Week */
            week: number;
            /**
             * Is Playoff
             * @default false
             */
            is_playoff: boolean;
            /** Opponent Team Id */
            opponent_team_id?: number | null;
            /** Opponent Team Name */
            opponent_team_name?: string | null;
            /** Opponent Owner Name */
            opponent_owner_name?: string | null;
            /** Team Score */
            team_score?: number | null;
            /** Opponent Score */
            opponent_score?: number | null;
            /** Result */
            result?: string | null;
            /** Margin */
            margin?: number | null;
        };
        /** ScoringTrendPoint */
        ScoringTrendPoint: {
            /** Week */
            week: number;
            /** Team Score */
            team_score?: number | null;
            /** League Avg */
            league_avg?: number | null;
            /**
             * Is Playoff
             * @default false
             */
            is_playoff: boolean;
        };
        /** ScoringWeek */
        ScoringWeek: {
            /** Week */
            week: number;
            /** Points */
            points?: number | null;
            /**
             * Breakdown
             * @default {}
             */
            breakdown: {
                [key: string]: unknown;
            };
        };
        /** SearchHit */
        SearchHit: {
            /** Type */
            type: string;
            /** Id */
            id: number;
            /** Label */
            label: string;
            /** Sublabel */
            sublabel?: string | null;
            /** Href */
            href: string;
        };
        /** SearchResults */
        SearchResults: {
            /** Query */
            query: string;
            /** Hits */
            hits: components["schemas"]["SearchHit"][];
        };
        /** SeasonList */
        SeasonList: {
            /** Seasons */
            seasons: components["schemas"]["SeasonListItem"][];
        };
        /** SeasonListItem */
        SeasonListItem: {
            /** Season Id */
            season_id: number;
            /** Season Year */
            season_year: number;
            /** Status */
            status?: string | null;
            /** Is Scored */
            is_scored: boolean;
            champion?: components["schemas"]["TeamRef"] | null;
        };
        /** SeasonSummary */
        SeasonSummary: {
            /** Season Id */
            season_id: number;
            /** Season Year */
            season_year: number;
            /** Status */
            status?: string | null;
            /** Regular Season Weeks */
            regular_season_weeks?: number | null;
            /** Playoff Weeks */
            playoff_weeks?: number | null;
            champion?: components["schemas"]["TeamRef"] | null;
            runner_up?: components["schemas"]["TeamRef"] | null;
            last_place?: components["schemas"]["TeamRef"] | null;
        };
        /** SeasonTotal */
        SeasonTotal: {
            /** Player Id */
            player_id: number;
            /** Name Full */
            name_full: string;
            /** Position */
            position?: string | null;
            /** Nfl Team */
            nfl_team?: string | null;
            /** Total Points */
            total_points: number;
            /** Weeks Played */
            weeks_played: number;
        };
        /** SeasonTotals */
        SeasonTotals: {
            /** Season Year */
            season_year: number;
            /** Position */
            position?: string | null;
            /** Totals */
            totals: components["schemas"]["SeasonTotal"][];
        };
        /** StandingRow */
        StandingRow: {
            /** Rank */
            rank: number;
            /** Team Id */
            team_id: number;
            /** Team Name */
            team_name?: string | null;
            /** Owner Id */
            owner_id: number;
            /** Owner Name */
            owner_name?: string | null;
            /** Wins */
            wins: number;
            /** Losses */
            losses: number;
            /** Ties */
            ties: number;
            /** Points For */
            points_for: number;
            /** Points Against */
            points_against: number;
            /** Win Pct */
            win_pct: number;
            streak: components["schemas"]["Streak"];
            /** Final Rank */
            final_rank?: number | null;
        };
        /** Standings */
        Standings: {
            /** Season Id */
            season_id: number;
            /** Season Year */
            season_year: number;
            /** Through Week */
            through_week: number;
            /** Regular Season Weeks */
            regular_season_weeks: number;
            /** Rank Basis */
            rank_basis: string;
            /** Tiebreak Caveat */
            tiebreak_caveat: boolean;
            /** Rows */
            rows: components["schemas"]["StandingRow"][];
        };
        /** StandingsTimeline */
        StandingsTimeline: {
            /** Season Id */
            season_id: number;
            /** Season Year */
            season_year: number;
            /** Regular Season Weeks */
            regular_season_weeks: number;
            /** Teams */
            teams: components["schemas"]["TimelineTeam"][];
        };
        /** Streak */
        Streak: {
            /** Result */
            result?: string | null;
            /**
             * Length
             * @default 0
             */
            length: number;
        };
        /** TeamOverview */
        TeamOverview: {
            /** Team Id */
            team_id: number;
            /** Team Name */
            team_name?: string | null;
            /** Season Id */
            season_id: number;
            /** Season Year */
            season_year: number;
            /** Owner Id */
            owner_id: number;
            /** Owner Name */
            owner_name?: string | null;
            /** Rank */
            rank?: number | null;
            /** Rank Basis */
            rank_basis: string;
            /** Wins */
            wins: number;
            /** Losses */
            losses: number;
            /** Ties */
            ties: number;
            /** Points For */
            points_for: number;
            /** Points Against */
            points_against: number;
            /** Final Rank */
            final_rank?: number | null;
            /** Made Playoffs */
            made_playoffs?: boolean | null;
            /** Is Champion */
            is_champion: boolean;
            /** Is Scored */
            is_scored: boolean;
        };
        /** TeamRef */
        TeamRef: {
            /** Team Id */
            team_id: number;
            /** Team Name */
            team_name?: string | null;
            /** Owner Id */
            owner_id?: number | null;
            /** Owner Name */
            owner_name?: string | null;
        };
        /** TeamRosterOut */
        TeamRosterOut: {
            /** Team Id */
            team_id: number;
            /** Season Year */
            season_year: number;
            /** Week */
            week: number;
            /** Weeks Available */
            weeks_available: number[];
            /** Is Scored */
            is_scored: boolean;
            /** Players */
            players: components["schemas"]["TeamRosterPlayer"][];
        };
        /** TeamRosterPlayer */
        TeamRosterPlayer: {
            /** Player Id */
            player_id: number;
            /** Player Name */
            player_name?: string | null;
            /** Position */
            position?: string | null;
            /** Nfl Team */
            nfl_team?: string | null;
            /** Roster Slot */
            roster_slot?: string | null;
            /** Is Starter */
            is_starter: boolean;
            /** League Points */
            league_points?: number | null;
            /** Acquisition Type */
            acquisition_type?: string | null;
            /** Acquisition Week */
            acquisition_week?: number | null;
        };
        /** TeamSchedule */
        TeamSchedule: {
            /** Team Id */
            team_id: number;
            /** Season Year */
            season_year: number;
            /** Games */
            games: components["schemas"]["ScheduleGame"][];
        };
        /** TeamScoringTrend */
        TeamScoringTrend: {
            /** Team Id */
            team_id: number;
            /** Season Year */
            season_year: number;
            /** Is Scored */
            is_scored: boolean;
            /** Points */
            points: components["schemas"]["ScoringTrendPoint"][];
        };
        /** TeamTransaction */
        TeamTransaction: {
            /** Transaction Id */
            transaction_id: number;
            /** Transaction Type */
            transaction_type: string;
            /** Executed At */
            executed_at?: string | null;
            /** Effective Week */
            effective_week?: number | null;
            /** Player Id */
            player_id?: number | null;
            /** Player Name */
            player_name?: string | null;
            /** Direction */
            direction?: string | null;
            /** Counterpart Team Id */
            counterpart_team_id?: number | null;
            /** Counterpart Team Name */
            counterpart_team_name?: string | null;
            /** Notes */
            notes?: string | null;
        };
        /** TeamTransactions */
        TeamTransactions: {
            /** Team Id */
            team_id: number;
            /** Season Year */
            season_year: number;
            /** Transactions */
            transactions: components["schemas"]["TeamTransaction"][];
        };
        /** TimelinePoint */
        TimelinePoint: {
            /** Week */
            week: number;
            /** Rank */
            rank: number;
            /** Points For */
            points_for: number;
        };
        /** TimelineTeam */
        TimelineTeam: {
            /** Team Id */
            team_id: number;
            /** Team Name */
            team_name?: string | null;
            /** Owner Id */
            owner_id: number;
            /** Owner Name */
            owner_name?: string | null;
            /** Points */
            points: components["schemas"]["TimelinePoint"][];
        };
        /** TopScorer */
        TopScorer: {
            /** Player Id */
            player_id: number;
            /** Name Full */
            name_full: string;
            /** Position */
            position?: string | null;
            /** Nfl Team */
            nfl_team?: string | null;
            /** Season Year */
            season_year: number;
            /** Week */
            week?: number | null;
            /** Points */
            points: number;
        };
        /** TopScorers */
        TopScorers: {
            /** Season Year */
            season_year: number;
            /** Week */
            week?: number | null;
            /** Position */
            position?: string | null;
            /** Scorers */
            scorers: components["schemas"]["TopScorer"][];
        };
        /** TrajectoryPoint */
        TrajectoryPoint: {
            /** Season Year */
            season_year?: number | null;
            /** Final Rank */
            final_rank?: number | null;
            /** Points For */
            points_for: number;
        };
        /** TrophyEntry */
        TrophyEntry: {
            /** Season Year */
            season_year?: number | null;
            /** Team Name */
            team_name?: string | null;
            /** Finish */
            finish?: number | null;
            /** Is Champion */
            is_champion: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WeekMatchups */
        WeekMatchups: {
            /** Season Id */
            season_id: number;
            /** Season Year */
            season_year: number;
            /** Week */
            week: number;
            /** Is Scored */
            is_scored: boolean;
            /** Games */
            games: components["schemas"]["GameCard"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    meta_v1_meta_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_MetaResponse_"];
                };
            };
        };
    };
    list_seasons_v1_seasons_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_SeasonList_"];
                };
            };
        };
    };
    get_season_summary_v1_seasons__season_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                season_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_SeasonSummary_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_standings_v1_seasons__season_id__standings_get: {
        parameters: {
            query?: {
                through_week?: number | null;
            };
            header?: never;
            path: {
                season_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_Standings_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_standings_timeline_v1_seasons__season_id__standings_timeline_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                season_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_StandingsTimeline_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_owners_v1_owners_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_OwnersList_"];
                };
            };
        };
    };
    get_rivalry_matrix_v1_owners_rivalry_matrix_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_RivalryMatrix_"];
                };
            };
        };
    };
    get_owner_career_v1_owners__owner_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                owner_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_OwnerCareer_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_owner_seasons_v1_owners__owner_id__seasons_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                owner_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_OwnerSeasons_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_owner_trajectory_v1_owners__owner_id__trajectory_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                owner_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_OwnerTrajectory_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_head_to_head_v1_owners__owner_id__head_to_head__other_owner_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                owner_id: number;
                other_owner_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_HeadToHead_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_records_v1_records_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_RecordsBook_"];
                };
            };
        };
    };
    get_championships_v1_records_championships_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_ChampionshipHistory_"];
                };
            };
        };
    };
    get_draft_records_v1_records_draft_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_DraftRecords_"];
                };
            };
        };
    };
    list_players_v1_players_get: {
        parameters: {
            query?: {
                name?: string | null;
                position?: string | null;
                nfl_team?: string | null;
                active?: boolean | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_PlayerIndex_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_player_detail_v1_players__player_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                player_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_PlayerOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_player_scoring_v1_players__player_id__scoring_get: {
        parameters: {
            query: {
                season: number;
            };
            header?: never;
            path: {
                player_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_PlayerScoring_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_player_ownership_v1_players__player_id__ownership_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                player_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_PlayerOwnership_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_player_availability_v1_players__player_id__availability_get: {
        parameters: {
            query: {
                season: number;
            };
            header?: never;
            path: {
                player_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_PlayerAvailability_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_top_scorers_v1_stats_top_scorers_get: {
        parameters: {
            query: {
                season: number;
                week?: number | null;
                position?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_TopScorers_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_season_totals_v1_stats_season_totals_get: {
        parameters: {
            query: {
                season: number;
                position?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_SeasonTotals_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_week_matchups_v1_seasons__season_id__weeks__week__matchups_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                season_id: number;
                week: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_WeekMatchups_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_box_score_v1_matchups__matchup_id__box_score_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                matchup_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_BoxScore_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_draft_board_v1_seasons__season_id__draft_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                season_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_DraftBoard_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_draft_value_v1_seasons__season_id__draft_value_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                season_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_DraftValue_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_power_ranking_v1_seasons__season_id__power_get: {
        parameters: {
            query?: {
                through_week?: number | null;
            };
            header?: never;
            path: {
                season_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_PowerRanking_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_power_timeline_v1_seasons__season_id__power_timeline_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                season_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_PowerTimeline_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_team_overview_v1_teams__team_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                team_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_TeamOverview_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_team_roster_v1_teams__team_id__roster_get: {
        parameters: {
            query?: {
                week?: number | null;
            };
            header?: never;
            path: {
                team_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_TeamRosterOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_team_schedule_v1_teams__team_id__schedule_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                team_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_TeamSchedule_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_team_scoring_trend_v1_teams__team_id__scoring_trend_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                team_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_TeamScoringTrend_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_team_transactions_v1_teams__team_id__transactions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                team_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_TeamTransactions_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_v1_search_get: {
        parameters: {
            query: {
                /** @description Search text */
                q: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_SearchResults_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
